### PR TITLE
Update models

### PR DESCRIPTION
**Pull request by Karry**
see individual commits for details

### CODE REVIEW

**Comment by piggz** [comment]
thanks, testing

**Comment by Karry** [comment]
So, what is your impression? :-)

**Comment by piggz** [comment]
Ive been having problems with advanced-cam and my pro1, where switching caameras isnt working well.  Any such issues for you?  What device do you have?

**Comment by Karry** [comment]
I have Sony Xperia 10 II. Switching cameras works fine for me. What are the symptoms on Pro1?

**Comment by piggz** [comment]
When selecting the front camera, it switch back to the rear ... when re-selecting the rear, it gets stuck in some kit of infinit loop updating models.  Im set up for debugging it now.

**Comment by Karry** [comment]
I had that issue too. Take a look to my second merge request: https://github.com/piggz/harbour-advanced-camera/pull/119 Especially to commit https://github.com/piggz/harbour-advanced-camera/pull/119/commits/3a3b5f5850f768750e87b1f98dbc69e611deb21c

**Comment by piggz** [comment]
Ah ok, i was trying to review them seperately!:D

**Comment by piggz** [comment]
Oh, totally my fault, i ddint even notice that first PR, i thought you just had this and the media metadata one!

**Comment by piggz** [comment]
Thanksyou!

**Comment by Karry** [comment]
You are wellcome :-) Thank you for this app!

**Pull request merged**
