### PR TITLE
use focus and snap hardware buttons

### PR DESCRIPTION
**Pull request by jgibbon**
Replacement for #57 with the much better solution you basically provided yourself.

cheers!

### CODE REVIEW

**Comment by jgibbon** [comment]
FYI, just rebased on the white space changes in the fix-manual branch.

**Comment by jgibbon** [comment]
Some more Info to simplify testing:
 - recent build on http://repo.merproject.org/obs/home:/velox:/testing/sailfish_latest_armv7hl/armv7hl/harbour-advanced-camera-0.4.0+shutter.buttons.20190926112711.26ade0d-1.11.1.jolla.armv7hl.rpm
 - Focus (lightly tap on camera button) is only enabled in "manual focus" mode (which is why this branch is based upon fix-manual). It is not restricted to photo mode, though, and should also work while recording video.
 - Snap (press down): Exactly the same functionality as the on screen button – practically unchanged.
 - Snap button (long-)press with advanced-camera in foreground should not open jolla-camera. The resource should be released when in background or closed and jolla-camera should start again as usual.


cheers!

**Comment by llelectronics** [comment]
Works for me

**Comment by mlehtima** [comment]
Maybe also add [some_tag] to beginning of commit message, check the commit history for examples.

**Comment by jgibbon** [comment]
Changes:
 - proposed white space added
 - removed "auto format" white space
 - commit message altered to include [buttons] tag

I checked in with @piggz – I'll make the "===" changes as a different PR to get to test that without hurry and still getting a new release ready soon. I'll create an issue to remember.

cheers!

**Pull request merged**
